### ISSUE TITLE
replace scala-meta macro annotations with scalamacros

### ISSUE THREAD

**Issue by kailuowang** [typelevel/cats-tagless#37]
This migration involves three areas of logic, in priority high to low order.  We can do these in separate PRs. 

- [x] derivation instances for algebra without abstract type members - one that generates default instances using the `cats.tagless.Derive` . e.g. 
```scala
  implicit val functorKForAlg: FunctorK[Alg] =
      Derive.functorK[Alg]
```
This need to handle situation where Alg with extra type params other than the effect type
The actual derivation is provide by the `cats.tagless.Derive` from the cats-tagless-macro module, the annotation just need to generate delegate methods (main challenge is to deal with different shapes of Alg types).

- [ ] derivation instances for algebra with abstract type members. We need normal instances and instances that are fully refined under an object in the companion named `fullyRefined` , see https://github.com/typelevel/cats-tagless/blob/master/legacy-macros/src/main/scala/cats/tagless/autoFunctorK.scala#L72
for existing scala meta implementation. again the actual derivation is supported by the `cats.tagless.Derive` from the cats-tagless-macro module
 
- [x] optional, alg instance summoning method like `def apply[F[_]](implicit ev: Alg[F]): Alg[F]`

**Comment by marcin-rzeznicki** [comment]
Hey, thanks for the issue. I am given some paid time from my company to participate in Sustainability Program, so I thought I could give it a try - I obviously don't want to step in anyone's toes, so please let me know if someone is already working on this, but if not I think I could take care of it.

**Comment by kailuowang** [comment]
cc @joroKr21

**Comment by dispalt** [comment]
I sorta half started working on it here, https://github.com/dispalt/tagless-redux/blob/master/macros/src/main/scala/cats/tagless/autoFunctorK.scala but it is far from complete, and the code is really messy.  But if you wanted to look at something there you go.

I am not going to work on it anytime soon (unfortunately).

**Comment by joroKr21** [comment]
I am not working on this actively atm. I would be very happy if you can make this happen. Even if you get only part of the way,  don't be shy to open a PR and I will do my best to help.

All I did was remove some code which became unused after delegating companion methods to the generated instances. Just to reduce the surface area. I will push it later tonight.

**Comment by joroKr21** [comment]
> All I did was remove some code which became unused after delegating companion methods to the generated instances. Just to reduce the surface area. I will push it later tonight.

Here it is: #38

**Comment by marcin-rzeznicki** [comment]
Thanks guys, I'll take a stab at it

**Comment by marcin-rzeznicki** [comment]
Hey, I opened a WIP PR #43 to show some progress. Please take a look! Thanks

**Comment by marcin-rzeznicki** [comment]
So, I am almost done with all the annotations. I am currently facing a minor issue where `Derive` macros are overriding type member which is defined also in the refinement resulting in something like:
```

**Comment by joroKr21** [comment]
Hmm I wonder why the existing tests didn't catch this :thinking:
Do you have a failing test?
It would help fixing the issue.

**Comment by joroKr21** [comment]
I get this on master so maybe something related to the migration
```scala
final class $anon extends cats.tagless.FunctorK[[Ƒ[_]]cats.tagless.tests.autoFunctorKTests.AlgWithAbstractTypeClass[Ƒ]{type TC[T] = TC0[T]}] {
  override def mapK[F[_] >: [_]Nothing <: [_]Any, G[_] >: [_]Nothing <: [_]Any](af: cats.tagless.tests.autoFunctorKTests.AlgWithAbstractTypeClass[F]{type TC[T] = TC0[T]})(fk: F ~> G): cats.tagless.tests.autoFunctorKTests.AlgWithAbstractTypeClass[G]{type TC[T] = TC0[T]} = {
    final class $anon extends cats.tagless.tests.autoFunctorKTests.AlgWithAbstractTypeClass[G] {
      type TC[T] = TC0[T];
      override def a[T](t: T)(implicit evidence$1: af.TC[T]): G[String] = fk(af.a[T](t)(evidence$1))
    };
    new $anon()
  }
}
```

If you push your latest changes I can take a look.

**Comment by marcin-rzeznicki** [comment]
Well, tests didn't catch this because shape of types have changed slightly during migration. The "old" code was creating a type-lambda everytime eg. `cats.tagless.InvariantK[({ type λ[Ƒ[_]] = AlgWithTypeMember[Ƒ] { type T = T0 } })#λ]` For me it was somehow easier to write it that type lambda is only created when needed, that is whenever the algebra contains more type parameters than one. So the new code is passing `cats.tagless.InvariantK[AlgWithTypeMember { type T = T0 }]` instead. This  makes the difference because the code that checks refined types https://github.com/typelevel/cats-tagless/blob/7c723042e9872ccd99f7bad3e667f66e4b6096a2/macros/src/main/scala/cats/tagless/DeriveMacros.scala#L119 will get it once (as it is non abstract in refined scope) *and* the piece that delegates abstract members will get it for the second time https://github.com/typelevel/cats-tagless/blob/7c723042e9872ccd99f7bad3e667f66e4b6096a2/macros/src/main/scala/cats/tagless/DeriveMacros.scala#L80 (cause it is abstract in defining type - I believe). So the fix is to slighlty reorganize the code and check like this `signature = tpe.typeSignatureIn(algebra) if signature.typeSymbol.isAbstract` and _voila_ :smile:

**Comment by joroKr21** [comment]
> cats.tagless.InvariantK[AlgWithTypeMember { type T = T0 }]

I didn't know this was legal Scala syntax :smile: You live and you learn.

I will check later for a fix. I'm not sure I follow what you proposed. But in general if it's not abstract in the refinement, well then it should not be abstract when delegating the types. So maybe this type has a shape which is somehow not handled by the macro, but I'm not sure.

**Comment by joroKr21** [comment]
Something's wrong here:
```scala
println(af.typeSignature)
// cats.tagless.tests.autoFunctorKTests.AlgWithAbstractTypeClass[F]{type TC[T] = List[T]}
println(af.typeSignature.member(TypeName("TC")).isAbstract)
// true
```

**Comment by marcin-rzeznicki** [comment]
> > cats.tagless.InvariantK[AlgWithTypeMember { type T = T0 }]
> 
> I didn't know this was legal Scala syntax smile You live and you learn.
> 

Haha - me neither :-)

> I will check later for a fix. I'm not sure I follow what you proposed. But in general if it's not abstract in the refinement, well then it should not be abstract when delegating the types. So maybe this type has a shape which is somehow not handled by the macro, but I'm not sure.

What I think is happening is that the check for abstractness `member.isAbstract` is not that robust - a "better" check (at least solving the problem I mentioned) is `..typeSignatureIn(algebra).typeSymbol.isAbstract` - this way we do not try to delegate members that are refined (but abstract in a declaring type - if I understand it correctly). I think that examples you pasted show exactly that, but I am not sure. All in all, after this change tests start passing :-) I'll open PR today hopefully

**Comment by joroKr21** [comment]
> .typeSignatureIn(algebra).typeSymbol.isAbstract

Looks like that breaks the definition with type lambdas.
This looks like a bug in scalac, but I'm still trying to figure out how to work around it.

**Comment by marcin-rzeznicki** [comment]
Ah, interesting :-) For now this works for me with no glitches :thinking:

**Comment by joroKr21** [comment]
Found the fix (idk why it took me so long :smile: ):
```diff
   def functorK[Alg[_[_]]](implicit tag: c.WeakTypeTag[Alg[Any]]): c.Tree = {
-    val Alg = tag.tpe.typeConstructor.dealias
+    val Alg = tag.tpe.typeConstructor.dealias.etaExpand
     instantiate(symbolOf[FunctorK[Any]], Alg)(mapK(Alg))
   }
```

**Comment by marcin-rzeznicki** [comment]
Actually, there are glitches. Sometimes it leads to 
```
[error] overriding method mapK in trait FunctorK of type [F[_], G[_]](af: cats.tagless.tests.autoFunctorKTests.AlgWithTypeMember[F]{type T = T0})(fk: F ~> G)cats.tagless.tests.autoFunctorKTests.AlgWithTypeMember[G]{type T = T0};
[error]  method mapK has incompatible type
``` etc. So I've reverted to the old behavior with type lambdas :smiley:

**Comment by marcin-rzeznicki** [comment]
Super, thx @joroKr21

**Comment by marcin-rzeznicki** [comment]
Please review #45. I hope it fixes all the tasks to complete migration

**Comment by marcin-rzeznicki** [comment]
Now that we have merged #45 maybe we can check off some items (possibly all)?

**Comment by joroKr21** [comment]
We have two issues about this ATM (this one and #6).
We can probably close one of them.

Do we want to define the `fullyRefined` instances for all supported typeclasses?
If we do it might be a good idea to put it behind a flag.

We might want to open a separate issue for Intellij support.

**Comment by marcin-rzeznicki** [comment]
Well, for one thing if there are no abstract type members in the algebra itself then there i no need to generate it, as it is indistinguishable from non-fully-refined instance. But I guess it is important to have this regularity for algebra consumers. The other point is that companion's generated methods are sufficient for correct inference etc. as they return fully-refined instances through dependent types. We might hide it under the flag as well.

**Comment by joroKr21** [comment]
I think it's time to close this issue.

The migration was done in #45 by @marcin-rzeznicki. Many thanks! :heart: 

I opened #59 for `fullyRefined` and #60 for the Intellij plugin to focus efforts.

**Comment by marcin-rzeznicki** [comment]
Thank you, I can take a stab at the remaining issues. Currently I'm on a short vacation so maybe some time next week
